version: '3'
services:
  mysql:
    container_name: "cmi-mysql"
    build:
      context: ../../docker/mysql
      dockerfile: Dockerfile
    volumes:
      - ../../data/mysql:/var/lib/mysql
      - ../../docker/mysql/init/00-init.sql:/docker-entrypoint-initdb.d/00-init.sql:ro
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "docker-healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    links:
      - cmi-api